# Generated by Django 5.2.4 on 2025-07-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["phone"], name="accounts_cu_phone_c30b3c_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["telegram_id"], name="accounts_cu_telegra_d09b11_idx"
            ),
        ),
    ]
