# Generated by Django 5.2.4 on 2025-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_kpiweights'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_inquiries', models.IntegerField(help_text='Minimum inquiries in this bracket (inclusive)')),
                ('max_inquiries', models.IntegerField(blank=True, help_text='Maximum inquiries in bracket (inclusive). Leave null for unlimited.', null=True)),
                ('excellent_threshold', models.FloatField(help_text='Minimum overall performance percentage for Excellent grade. Below this is considered average performance.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this target configuration is active')),
            ],
            options={
                'verbose_name': 'Performance Target',
                'verbose_name_plural': 'Performance Targets',
                'ordering': ['min_inquiries'],
                'indexes': [models.Index(fields=['is_active'], name='inquiries_p_is_acti_9d85b9_idx'), models.Index(fields=['min_inquiries'], name='inquiries_p_min_inq_c10503_idx')],
            },
        ),
    ]
