# Generated by Django 5.2.4 on 2026-08-13 10:49

import django.core.validators
from django.db import migrations, models

import apps.inquiries.models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0005_performancetarget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="inquiry_attachments/%Y/%m/%d/",
                validators=[
                    apps.inquiries.models.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "webp",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "csv",
                            "txt",
                        ]
                    ),
                ],
            ),
        ),
    ]
